# Generated by Django 5.1.4 on 2024-12-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=255)),
                ('room', models.IntegerField()),
                ('square_m', models.FloatField()),
                ('floor', models.IntegerField()),
                ('max_floor', models.IntegerField()),
                ('block', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('completion', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('windows', models.IntegerField()),
                ('builder', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fixation',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to='system.apartment')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to='system.buyer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to='system.user')),
            ],
        ),
    ]
