# Generated by Django 5.1.4 on 2025-02-23 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_fixation_user_alter_apartment_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='block',
            field=models.CharField(max_length=50, verbose_name='Пятно'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='builder',
            field=models.CharField(max_length=50, verbose_name='Застройщик'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='completion',
            field=models.DateField(verbose_name='Отделка'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='max_floor',
            field=models.IntegerField(verbose_name='Макс. Этажей'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='object',
            field=models.CharField(max_length=255, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='quantity',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room',
            field=models.IntegerField(verbose_name='Комнат'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='square_m',
            field=models.FloatField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='windows',
            field=models.CharField(max_length=255, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to='system.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to='system.buyer', verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fixation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixations', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
