# Generated by Django 5.1.4 on 2025-02-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_fixation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixation',
            name='prolong_count',
            field=models.IntegerField(default=0),
        ),
    ]
