# Generated by Django 5.1.4 on 2025-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_fixation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixation',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'АКТИВНЫЙ'), ('QUEUE', 'В ОЧЕРЕДИ')], default='QUEUE', max_length=50),
        ),
    ]
