# Generated by Django 5.1.4 on 2025-03-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_debt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='unique_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='unique_id',
            new_name='id',
        ),
    ]
