# Generated by Django 5.1.4 on 2025-03-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_rename_unique_id_apartment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixation',
            old_name='unique_id',
            new_name='id',
        ),
    ]
