# Generated by Django 5.1.4 on 2025-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_rename_unique_id_fixation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='completion',
            field=models.CharField(verbose_name='Сдача'),
        ),
    ]
