# Generated by Django 5.1.4 on 2025-03-04 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_apartment_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_data', models.JSONField(default=list)),
                ('fixation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='system.fixation')),
            ],
        ),
    ]
