# Generated by Django 5.1.4 on 2025-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_fixationhistory_fixation_id_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='debt',
            name='fix_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
