# Generated by Django 5.1.4 on 2025-03-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_debt_amount_debt_fix_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='amount',
            new_name='debt_sum',
        ),
    ]
